-- Création de la table Pokemon
DROP TABLE IF EXISTS Pokemon;
CREATE TABLE IF NOT EXISTS Pokemon (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    pokedexId INTEGER,
    name TEXT,
    image TEXT,
    sprite TEXT,
    slug TEXT,
    hp INTEGER,
    attack INTEGER,
    defense INTEGER,
    special_attack INTEGER,
    special_defense INTEGER,
    speed INTEGER,
    generation INTEGER,
    type1 TEXT,
    type2 TEXT,
    pre_evolution_name TEXT,
    pre_evolution_pokedex_id INTEGER,
    evolution_name TEXT,
    evolution_pokedex_id INTEGER
);

-- Création de la table PokemonResistance
DROP TABLE IF EXISTS PokemonResistance;
CREATE TABLE IF NOT EXISTS PokemonResistance (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    pokemon_id INTEGER,
    resistance_name TEXT,
    damage_multiplier REAL,
    damage_relation TEXT,
    FOREIGN KEY (pokemon_id) REFERENCES Pokemon(id)
);

-- Insertion des données des Pokémon
INSERT INTO Pokemon (id, pokedexId, name, image, sprite, slug, hp, attack, defense, special_attack, special_defense, speed, generation, type1, type2, pre_evolution_name, pre_evolution_pokedex_id, evolution_name, evolution_pokedex_id)
VALUES
(1, 1, 'Bulbizarre', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/1.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1.png', 'Bulbizarre', 45, 49, 49, 65, 65, 45, 1, 'Poison', 'Plante', NULL, NULL, 'Herbizarre', 2),
(2, 2, 'Herbizarre', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/2.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/2.png', 'Herbizarre', 60, 62, 63, 80, 80, 60, 1, 'Poison', 'Plante', 'Bulbizarre', 1, 'Florizarre', 3),
(3, 3, 'Florizarre', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/3.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/3.png', 'Florizarre', 80, 82, 83, 100, 100, 80, 1, 'Poison', 'Plante', 'Herbizarre', 2, NULL, NULL),
(4, 4, 'Salamèche', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/4.png', 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/4.png', 'Salameche', 39, 52, 43, 60, 50, 65, 1, 'Feu', NULL, NULL, NULL, 'Reptincel', 5);

-- Insertion des données dans la table PokemonResistance
INSERT INTO PokemonResistance (pokemon_id, resistance_name, damage_multiplier, damage_relation)
VALUES
(1, 'Normal', 1, 'neutral'),
(1, 'Combat', 0.5, 'resistant'),
(1, 'Vol', 2, 'vulnerable'),
(1, 'Poison', 1, 'neutral'),
(1, 'Sol', 1, 'neutral'),
(1, 'Roche', 1, 'neutral'),
(1, 'Insecte', 1, 'neutral'),
(1, 'Spectre', 1, 'neutral'),
(1, 'Acier', 1, 'neutral'),
(1, 'Feu', 2, 'vulnerable'),
(1, 'Eau', 0.5, 'resistant'),
(1, 'Plante', 0.25, 'twice_resistant'),
(1, 'Électrik', 0.5, 'resistant'),
(1, 'Psy', 2, 'vulnerable'),
(1, 'Glace', 2, 'vulnerable'),
(1, 'Dragon', 1, 'neutral'),
(1, 'Ténèbres', 1, 'neutral'),
(1, 'Fée', 0.5, 'resistant'),
(2, 'Normal', 1, 'neutral'),
(2, 'Combat', 0.5, 'resistant'),
(2, 'Vol', 2, 'vulnerable'),
(2, 'Poison', 1, 'neutral'),
(2, 'Sol', 1, 'neutral'),
(2, 'Roche', 1, 'neutral'),
(2, 'Insecte', 1, 'neutral'),
(2, 'Spectre', 1, 'neutral'),
(2, 'Acier', 1, 'neutral'),
(2, 'Feu', 2, 'vulnerable'),
(2, 'Eau', 0.5, 'resistant'),
(2, 'Plante', 0.25, 'twice_resistant'),
(2, 'Électrik', 0.5, 'resistant'),
(2, 'Psy', 2, 'vulnerable'),
(2, 'Glace', 2, 'vulnerable'),
(2, 'Dragon', 1, 'neutral'),
(2, 'Ténèbres', 1, 'neutral'),
(2, 'Fée', 0.5, 'resistant'),
(3, 'Normal', 1, 'neutral'),
(3, 'Combat', 0.5, 'resistant'),
(3, 'Vol', 2, 'vulnerable'),
(3, 'Poison', 1, 'neutral'),
(3, 'Sol', 1, 'neutral'),
(3, 'Roche', 1, 'neutral'),
(3, 'Insecte', 1, 'neutral'),
(3, 'Spectre', 1, 'neutral'),
(3, 'Acier', 1, 'neutral'),
(3, 'Feu', 2, 'vulnerable'),
(3, 'Eau', 0.5, 'resistant'),
(3, 'Plante', 0.25, 'twice_resistant'),
(3, 'Électrik', 0.5, 'resistant'),
(3, 'Psy', 2, 'vulnerable'),
(3, 'Glace', 2, 'vulnerable'),
(3, 'Dragon', 1, 'neutral'),
(3, 'Ténèbres', 1, 'neutral'),
(3, 'Fée', 0.5, 'resistant'),
(4, 'Normal', 1, 'neutral'),
(4, 'Combat', 1, 'neutral'),
(4, 'Vol', 1, 'neutral'),
(4, 'Poison', 1, 'neutral'),
(4, 'Sol', 2, 'vulnerable'),
(4, 'Roche', 2, 'vulnerable'),
(4, 'Insecte', 0.5, 'resistant'),
(4, 'Spectre', 1, 'neutral'),
(4, 'Acier', 0.5, 'resistant'),
(4, 'Feu', 0.5, 'resistant'),
(4, 'Eau', 2, 'vulnerable'),
(4, 'Plante', 0.5, 'resistant'),
(4, 'Électrik', 1, 'neutral'),
(4, 'Psy', 1, 'neutral'),
(4, 'Glace', 0.5, 'resistant'),
(4, 'Dragon', 1, 'neutral'),
(4, 'Ténèbres', 1, 'neutral'),
(4, 'Fée', 0.5, 'resistant');
